#Grundlegegende App config
quarkus.application.name=MyJavaBot-QuarkusEdition
bot.token=${DISCORD_BOT_TOKEN}
#GitHub Config
github.username=${GITHUB_USER_NAME}
github.token=${GITHUB_KEY}
github.repos=${GITHUB_REPOS}
#Discord IDs
discord.id.humunkulus=${DISCORD_ID_HUMUNKULUS}
discord.id.hamham=${DISCORD_ID_HAMHAM}
discord.id.max=${DISCORD_ID_MAX}
discord.id.soitzu=${DISCORD_ID_SOITZU}
discord.id.lobby1=${DISCORD_ID_LOBBY_1}
discord.id.lobby1.channel.ytmusic=${DISCORD_ID_LOBBY_1_CHANNEL_YT_MUSIC}
#Services
quarkus.rest-client.debt-api.url=${DEBT_API_URL}
#Misc
discord.twitter.betterEmbeds=${DISCORD_TWITTER_EMBEDS}
quarkus.native.additional-build-args=--initialize-at-run-time=com.neovisionaries.ws.client.Misc\\,net.dv8tion.jda
